package edu.cmu.monsterstem.state
{
	import com.citrusengine.physics.Box2D;
	import com.citrusengine.core.CitrusEngine;
	import com.citrusengine.core.State;
	import com.citrusengine.utils.ObjectMaker;
	import com.citrusengine.core.CitrusObject;
	import com.citrusengine.view.ISpriteView;
	/**
	 * ...
	 * @author Erik Harpstead
	 */
	public class GoldSpikeState extends State {
		private var _levelData:XML;
		
		public function GoldSpikeState(levelData:XML) {
			//This is the level XML file that was generated by the Level Architect.
			_levelData = levelData;
		}
		
		override public function initialize():void {
			super.initialize();
			
			var box2D:Box2D = new Box2D("Box2d");
			add(box2D);
			
			//box2D.visible = true;
			
			if (_levelData)
				ObjectMaker.FromLevelArchitect(_levelData);
			
			for each (var co:CitrusObject in getObjectsByType(CitrusObject)) {
				CitrusEngine.dbg(co.name + " : " + (co is ISpriteView ? (co as ISpriteView).view : "")+"\n");
			}
		}
	}
}